### ISSUE TITLE
Update to Jameica 2.10

### ISSUE THREAD

**Issue by tobias-hammerschmidt** [flathub/de.willuhn.Jameica#1]
Jameica 2.10 was released on 2020-11-27

**Comment by tobias-hammerschmidt** [comment]
blocked due to exception:

```
Exception in thread "main" org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4895)
	at org.eclipse.swt.SWT.error(SWT.java:4784)
	at org.eclipse.swt.SWT.error(SWT.java:4755)
	at org.eclipse.swt.graphics.Cursor.<init>(Cursor.java:151)
	at org.eclipse.swt.widgets.Display.getSystemCursor(Display.java:2896)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:64)
	at de.willuhn.jameica.gui.GUI$6.run(GUI.java:911)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5855)
	at de.willuhn.jameica.gui.GUI.startSync(GUI.java:907)
	at de.willuhn.jameica.gui.parts.Button$1.widgetSelected(Button.java:168)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5745)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5013)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4507)
	at de.willuhn.jameica.gui.dialogs.AbstractDialog$4.run(AbstractDialog.java:559)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5855)
	at de.willuhn.jameica.gui.dialogs.AbstractDialog.open(AbstractDialog.java:484)
	at de.willuhn.jameica.system.ApplicationCallbackSWT.createPassword(ApplicationCallbackSWT.java:98)
	at de.willuhn.jameica.security.SSLFactory.init(SSLFactory.java:303)
	at de.willuhn.jameica.services.SSLService.init(SSLService.java:45)
	at de.willuhn.boot.BootLoader.resolve(BootLoader.java:139)
	at de.willuhn.boot.BootLoader.resolve(BootLoader.java:119)
	at de.willuhn.boot.BootLoader.resolve(BootLoader.java:119)
	at de.willuhn.boot.BootLoader.getBootable(BootLoader.java:70)
	at de.willuhn.jameica.system.Application.init(Application.java:103)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:75)
```

**Comment by tobias-hammerschmidt** [comment]
exception resolved by switching to gnome platform (like flatpak eclipse)

**Comment by tobias-hammerschmidt** [comment]
fixed by https://github.com/flathub/de.willuhn.Jameica/commit/47e2dba181b87baf044e9554f021ae472dc372b0
