### ISSUE TITLE
Scripting plugin issue since update to Gnome 46 runtime update

### ISSUE THREAD

**Issue by webagentur-hartmann** [flathub/de.willuhn.Jameica#36]
Since the runtime was updated to Gnome 46 (#35) the plugin no longer works on my computer.

```
[Sun Jun 30 20:52:13 CEST 2024][ERROR][bg-task:Worker][de.derrichter.hibiscus.mashup.crossover.callback.WebLogger.error] [SeleniumUtils] WebDriver Task-Kill fehlgeschlagen! Stacktrace: java.io.IOException: Cannot run program "killall": error=2, Datei oder Verzeichnis nicht gefunden
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at de.derrichter.finance.websync.utils.webdrivertools.SeleniumUtils.quitBrowserDriver(SeleniumUtils.java:481)
	at de.derrichter.finance.websync.connector.ChromeDriverWebClientInit.connConfig(ChromeDriverWebClientInit.java:153)
	at de.derrichter.hibiscus.mashup.crossover.websync.institute.weltsparen.Collector.run(Collector.java:160)
	at de.derrichter.hibiscus.mashup.crossover.websync.WebSynchronizeJobKontoauszug.execute(WebSynchronizeJobKontoauszug.java:84)
	at de.derrichter.hibiscus.mashup.crossover.websync.WebSynchronizeBackend$WebSyncJobGroup.sync(WebSynchronizeBackend.java:905)
	at de.willuhn.jameica.hbci.synchronize.AbstractSynchronizeBackend$Worker.run(AbstractSynchronizeBackend.java:399)
	at de.willuhn.jameica.gui.GUI$7.run(GUI.java:1107)
Caused by: java.io.IOException: error=2, Datei oder Verzeichnis nicht gefunden
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 8 more
```

**Comment by webagentur-hartmann** [comment]
It seems to be an issue with the chromedriver in version 126. The first appearance was on June 14th, 2024, one day after the first release of driver version 126 and three days before you merged the update to Gnome 46 runtime. Furthermore, it also appears on Windows machines.

Please see the following forum comment:

https://scripting-forum.derrichter.de/viewtopic.php?f=34&t=1666&start=10
https://scripting-forum.derrichter.de/viewtopic.php?f=34&t=1671

The mentioned comment #21 was about the missing webkit in Gnome runtime.

It seems that the current workaround is to manually downgrade the chromedriver to version 125 (https://hibiscus-mashup.derrichter.de/index.php/download/plugins-und-addons-stable), and to prevent an automatic update of the plugin.
